### ISSUE TITLE
Wrong number of arguments (4 for 3) for `rgb'

### ISSUE THREAD

**Issue by sorrat** [beyonk-adventures/svelte-notifications#4]
Traceback:
```
ERROR in ./node_modules/@beyonk/svelte-notifications/src/Notifications.svelte.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Wrong number of arguments (4 for 3) for `rgb'
      in ./node_modules/@beyonk/svelte-notifications/src/Notifications.svelte.css (line 1, column 362)
    at runLoaders (./node_modules/webpack/lib/NormalModule.js:313:20)
    at ./node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at ./node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (./node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.render [as callback] (./node_modules/sass-loader/lib/loader.js:90:7)
    at Object.done [as callback] (./node_modules/neo-async/async.js:8067:18)
    at options.error (./node_modules/node-sass/lib/index.js:294:32)
 @ ./node_modules/@beyonk/svelte-notifications/src/Notifications.svelte 297:0-118
[...]
```
No errors if I change `rgb` -> `rgba` in `Notifications.svelte`

**Comment by antony** [comment]
@sorrat interesting - I've not encountered this. Do you have a reproduction/some example code somewhere?

**Comment by sorrat** [comment]
The error happens when plain `.css` files are processed with `sass-loader`.
```js
{
  test: /\.(sa|sc|c)ss$/,
  use: [
     {loader: MiniCssExtractPlugin.loader},
    'css-loader',
    'sass-loader',
  ],
}
```

The error can be avoided by using separate rules for `.css` and `.sass` files.

**Comment by antony** [comment]
Interesting. I'm not sure why this would be the case, but it doesn't seem like an issue for this project. Possibly a bug in sass-loader?

I use `svelte-preprocess` and I haven't encountered this.
